export const data = {
    products: [
        { id: 1, 
          name: 'Apple Watch SE (2nd Gen) [GPS 44 mm] Smart Watch w/Starlight Aluminium Case', 
          price: 26999,
          image: '/images/apple.jpg',
          countInStock: 40,
          rating: 4.6,
          reviews: 2875,
          description: 'Smart Watch'  
        },
        { id: 2, 
            name: 'Samsung Galaxy Fit3 (Pink Gold), 40mm AMOLED Display with Aluminium Body', 
            price: 4499,
            image: '/images/samsungfit3.jpg',
            countInStock: 56,
            rating: 3.9,
            reviews: 627,
            description: 'Smart Watch'  
         },
        { id: 3, 
            name: 'Samsung Galaxy Watch Ultra (47mm, LTE, Gray) with Upto 100h Battery ', 
            price: 59999,
            image: '/images/samsung.jpg',
            countInStock: 9,
            rating: 3.6,
            reviews: 11,
            description: 'Smart Watch'  
        },
        { id: 4, 
            name: 'boAt Wave Call 2 w/ 1.83" (4.6 cm) HD Display Advanced Bluetooth Calling', 
            price: 1099,
            image: '/images/boatwave.jpg',
            countInStock: 38,
            rating: 3.9,
            reviews: 74374,
            description: 'Smart Watch'  
        },
        { id: 5, 
            name: 'Noise Pulse Go Buzz Smart Watch with Advanced Bluetooth Calling, TFT Display', 
            price: 999,
            image: '/images/noisepulz.jpg',
            countInStock: 400,
            rating: 4.1,
            reviews: 38806,
            description: 'Smart Watch'  
        },
        { id: 6, 
            name: 'Fastrack New Limitless X2 Smartwatch|1.91" UltraVU with Rotating Crown', 
            price: 1299,
            image: '/images/fastrackx2.jpg',
            countInStock: 46,
            rating: 3.1,
            reviews: 38536,
            description: 'Smart Watch'  
        },
    ],
}